# Generated by Django 3.2.12 on 2023-01-22 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ninad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ragadb',
            name='aaroh',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ragadb',
            name='aavaroh',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ragadb',
            name='naam',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ragadb',
            name='samvadi',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ragadb',
            name='thaat',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ragadb',
            name='time',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ragadb',
            name='vadi',
            field=models.TextField(),
        ),
    ]
